<?php

declare(strict_types=1);

namespace Larafocus\Companies\DTO;

use Larafocus\Companies\DTO\Enums\OrientacaoDanfe;
use Larafocus\Companies\DTO\Enums\RegimeTributario;
use Larafocus\Companies\DTO\Enums\SmtpAutenticacao;
use Larafocus\Companies\DTO\Enums\SmtpVerificacaoOpenssl;
use Larafocus\Shared\TypeCast;

/** @phpstan-type EmpresaRequestArray array{nome?: string|null, nome_fantasia?: string|null, cnpj?: string|null, cpf?: string|null, inscricao_estadual?: string|int|null, inscricao_municipal?: string|int|null, regime_tributario?: int|null, logradouro?: string|null, numero?: string|int|null, complemento?: string|null, bairro?: string|null, municipio?: string|null, cep?: string|int|null, uf?: string|null, telefone?: string|null, email?: string|null, habilita_nfe?: string|int|bool|null, habilita_nfce?: string|int|bool|null, habilita_nfse?: string|int|bool|null, habilita_nfsen_producao?: string|int|bool|null, habilita_nfsen_homologacao?: string|int|bool|null, habilita_cte?: string|int|bool|null, habilita_mdfe?: string|int|bool|null, habilita_nfcom?: string|int|bool|null, habilita_manifestacao?: string|int|bool|null, habilita_manifestacao_cte?: string|int|bool|null, habilita_nfsen_recebidas_producao?: string|int|bool|null, habilita_nfsen_recebidas_homologacao?: string|int|bool|null, enviar_email_destinatario?: string|int|bool|null, enviar_email_homologacao?: string|int|bool|null, discrimina_impostos?: string|int|bool|null, habilita_contingencia_offline_nfce?: string|int|bool|null, reaproveita_numero_nfce_contingencia?: string|int|bool|null, csc_nfce_producao?: string|null, id_token_nfce_producao?: string|int|null, csc_nfce_homologacao?: string|null, id_token_nfce_homologacao?: string|int|null, orientacao_danfe?: string|null, recibo_danfe?: string|int|bool|null, exibe_sempre_ipi_danfe?: string|int|bool|null, exibe_issqn_danfe?: string|int|bool|null, exibe_impostos_adicionais_danfe?: string|int|bool|null, exibe_rastro_danfe?: string|int|bool|null, exibe_unidade_tributaria_danfe?: string|int|bool|null, exibe_sempre_volumes_danfe?: string|int|bool|null, exibe_composicao_carga_mdfe?: string|int|bool|null, mostrar_danfse_badge?: string|int|bool|null, proximo_numero_nfe_producao?: string|null, proximo_numero_nfe_homologacao?: string|null, serie_nfe_producao?: string|null, serie_nfe_homologacao?: string|null, proximo_numero_nfce_producao?: string|null, proximo_numero_nfce_homologacao?: string|null, serie_nfce_producao?: string|null, serie_nfce_homologacao?: string|null, proximo_numero_nfse_producao?: string|null, proximo_numero_nfse_homologacao?: string|null, serie_nfse_producao?: string|null, serie_nfse_homologacao?: string|null, proximo_numero_nfsen_producao?: string|null, proximo_numero_nfsen_homologacao?: string|null, serie_nfsen_producao?: string|null, serie_nfsen_homologacao?: string|null, proximo_numero_cte_producao?: string|null, proximo_numero_cte_homologacao?: string|null, serie_cte_producao?: string|null, serie_cte_homologacao?: string|null, proximo_numero_cte_os_producao?: string|null, proximo_numero_cte_os_homologacao?: string|null, serie_cte_os_producao?: string|null, serie_cte_os_homologacao?: string|null, proximo_numero_mdfe_producao?: string|null, proximo_numero_mdfe_homologacao?: string|null, serie_mdfe_producao?: string|null, serie_mdfe_homologacao?: string|null, proximo_numero_nfcom_producao?: string|null, proximo_numero_nfcom_homologacao?: string|null, serie_nfcom_producao?: string|null, serie_nfcom_homologacao?: string|null, arquivo_certificado_base64?: string|null, senha_certificado?: string|null, arquivo_logo_base64?: string|null, delete_logo?: string|int|bool|null, nome_responsavel?: string|null, cpf_responsavel?: string|null, login_responsavel?: string|null, senha_responsavel?: string|null, senha_responsavel_preenchida?: string|int|bool|null, cpf_cnpj_contabilidade?: string|null, data_inicio_recebimento_nfe?: string|null, data_inicio_recebimento_cte?: string|null, smtp_endereco?: string|null, smtp_dominio?: string|null, smtp_porta?: string|int|null, smtp_autenticacao?: string|null, smtp_login?: string|null, smtp_senha?: string|null, smtp_remetente?: string|null, smtp_responder_para?: string|null, smtp_modo_verificacao_openssl?: string|null, smtp_habilita_starttls?: string|int|bool|null, smtp_ssl?: string|int|bool|null, smtp_tls?: string|int|bool|null, nfe_sincrono?: string|int|bool|null, nfe_sincrono_homologacao?: string|int|bool|null, mdfe_sincrono?: string|int|bool|null, mdfe_sincrono_homologacao?: string|int|bool|null} */
readonly class EmpresaRequest
{
    public function __construct(
        // Dados basicos
        public ?string $nome = null,
        public ?string $nome_fantasia = null,
        public ?string $cnpj = null,
        public ?string $cpf = null,
        public ?int $inscricao_estadual = null,
        public ?int $inscricao_municipal = null,
        public ?RegimeTributario $regime_tributario = null,

        // Endereco
        public ?string $logradouro = null,
        public ?int $numero = null,
        public ?string $complemento = null,
        public ?string $bairro = null,
        public ?string $municipio = null,
        public ?int $cep = null,
        public ?string $uf = null,

        // Contato
        public ?string $telefone = null,
        public ?string $email = null,

        // Habilitacoes de documentos
        public ?bool $habilita_nfe = null,
        public ?bool $habilita_nfce = null,
        public ?bool $habilita_nfse = null,
        public ?bool $habilita_nfsen_producao = null,
        public ?bool $habilita_nfsen_homologacao = null,
        public ?bool $habilita_cte = null,
        public ?bool $habilita_mdfe = null,
        public ?bool $habilita_nfcom = null,
        public ?bool $habilita_manifestacao = null,
        public ?bool $habilita_manifestacao_cte = null,
        public ?bool $habilita_nfsen_recebidas_producao = null,
        public ?bool $habilita_nfsen_recebidas_homologacao = null,

        // Comunicacao
        public ?bool $enviar_email_destinatario = null,
        public ?bool $enviar_email_homologacao = null,
        public ?bool $discrimina_impostos = null,

        // NFCe
        public ?bool $habilita_contingencia_offline_nfce = null,
        public ?bool $reaproveita_numero_nfce_contingencia = null,
        public ?string $csc_nfce_producao = null,
        public ?int $id_token_nfce_producao = null,
        public ?string $csc_nfce_homologacao = null,
        public ?int $id_token_nfce_homologacao = null,

        // DANFe
        public ?OrientacaoDanfe $orientacao_danfe = null,
        public ?bool $recibo_danfe = null,
        public ?bool $exibe_sempre_ipi_danfe = null,
        public ?bool $exibe_issqn_danfe = null,
        public ?bool $exibe_impostos_adicionais_danfe = null,
        public ?bool $exibe_rastro_danfe = null,
        public ?bool $exibe_unidade_tributaria_danfe = null,
        public ?bool $exibe_sempre_volumes_danfe = null,
        public ?bool $exibe_composicao_carga_mdfe = null,
        public ?bool $mostrar_danfse_badge = null,

        // Numeracao de documentos
        public ?string $proximo_numero_nfe_producao = null,
        public ?string $proximo_numero_nfe_homologacao = null,
        public ?string $serie_nfe_producao = null,
        public ?string $serie_nfe_homologacao = null,
        public ?string $proximo_numero_nfce_producao = null,
        public ?string $proximo_numero_nfce_homologacao = null,
        public ?string $serie_nfce_producao = null,
        public ?string $serie_nfce_homologacao = null,
        public ?string $proximo_numero_nfse_producao = null,
        public ?string $proximo_numero_nfse_homologacao = null,
        public ?string $serie_nfse_producao = null,
        public ?string $serie_nfse_homologacao = null,
        public ?string $proximo_numero_nfsen_producao = null,
        public ?string $proximo_numero_nfsen_homologacao = null,
        public ?string $serie_nfsen_producao = null,
        public ?string $serie_nfsen_homologacao = null,
        public ?string $proximo_numero_cte_producao = null,
        public ?string $proximo_numero_cte_homologacao = null,
        public ?string $serie_cte_producao = null,
        public ?string $serie_cte_homologacao = null,
        public ?string $proximo_numero_cte_os_producao = null,
        public ?string $proximo_numero_cte_os_homologacao = null,
        public ?string $serie_cte_os_producao = null,
        public ?string $serie_cte_os_homologacao = null,
        public ?string $proximo_numero_mdfe_producao = null,
        public ?string $proximo_numero_mdfe_homologacao = null,
        public ?string $serie_mdfe_producao = null,
        public ?string $serie_mdfe_homologacao = null,
        public ?string $proximo_numero_nfcom_producao = null,
        public ?string $proximo_numero_nfcom_homologacao = null,
        public ?string $serie_nfcom_producao = null,
        public ?string $serie_nfcom_homologacao = null,

        // Certificado digital
        public ?string $arquivo_certificado_base64 = null,
        public ?string $senha_certificado = null,

        // Logo
        public ?string $arquivo_logo_base64 = null,
        public ?bool $delete_logo = null,

        // Responsavel
        public ?string $nome_responsavel = null,
        public ?string $cpf_responsavel = null,
        public ?string $login_responsavel = null,
        public ?string $senha_responsavel = null,
        public ?bool $senha_responsavel_preenchida = null,

        // Contabilidade
        public ?string $cpf_cnpj_contabilidade = null,
        public ?string $data_inicio_recebimento_nfe = null,
        public ?string $data_inicio_recebimento_cte = null,

        // SMTP
        public ?string $smtp_endereco = null,
        public ?string $smtp_dominio = null,
        public ?int $smtp_porta = null,
        public ?SmtpAutenticacao $smtp_autenticacao = null,
        public ?string $smtp_login = null,
        public ?string $smtp_senha = null,
        public ?string $smtp_remetente = null,
        public ?string $smtp_responder_para = null,
        public ?SmtpVerificacaoOpenssl $smtp_modo_verificacao_openssl = null,
        public ?bool $smtp_habilita_starttls = null,
        public ?bool $smtp_ssl = null,
        public ?bool $smtp_tls = null,

        // Processamento sincrono
        public ?bool $nfe_sincrono = null,
        public ?bool $nfe_sincrono_homologacao = null,
        public ?bool $mdfe_sincrono = null,
        public ?bool $mdfe_sincrono_homologacao = null,
    ) {}

    /** @phpstan-param EmpresaRequestArray $data */
    public static function fromArray(array $data): self
    {
        return new self(
            nome: $data['nome'] ?? null,
            nome_fantasia: $data['nome_fantasia'] ?? null,
            cnpj: $data['cnpj'] ?? null,
            cpf: $data['cpf'] ?? null,
            inscricao_estadual: TypeCast::nullableInt($data['inscricao_estadual'] ?? null),
            inscricao_municipal: TypeCast::nullableInt($data['inscricao_municipal'] ?? null),
            regime_tributario: isset($data['regime_tributario'])
                ? RegimeTributario::from($data['regime_tributario'])
                : null,
            logradouro: $data['logradouro'] ?? null,
            numero: TypeCast::nullableInt($data['numero'] ?? null),
            complemento: $data['complemento'] ?? null,
            bairro: $data['bairro'] ?? null,
            municipio: $data['municipio'] ?? null,
            cep: TypeCast::nullableInt($data['cep'] ?? null),
            uf: $data['uf'] ?? null,
            telefone: $data['telefone'] ?? null,
            email: $data['email'] ?? null,
            habilita_nfe: TypeCast::nullableBool($data['habilita_nfe'] ?? null),
            habilita_nfce: TypeCast::nullableBool($data['habilita_nfce'] ?? null),
            habilita_nfse: TypeCast::nullableBool($data['habilita_nfse'] ?? null),
            habilita_nfsen_producao: TypeCast::nullableBool($data['habilita_nfsen_producao'] ?? null),
            habilita_nfsen_homologacao: TypeCast::nullableBool($data['habilita_nfsen_homologacao'] ?? null),
            habilita_cte: TypeCast::nullableBool($data['habilita_cte'] ?? null),
            habilita_mdfe: TypeCast::nullableBool($data['habilita_mdfe'] ?? null),
            habilita_nfcom: TypeCast::nullableBool($data['habilita_nfcom'] ?? null),
            habilita_manifestacao: TypeCast::nullableBool($data['habilita_manifestacao'] ?? null),
            habilita_manifestacao_cte: TypeCast::nullableBool($data['habilita_manifestacao_cte'] ?? null),
            habilita_nfsen_recebidas_producao: TypeCast::nullableBool($data['habilita_nfsen_recebidas_producao'] ?? null),
            habilita_nfsen_recebidas_homologacao: TypeCast::nullableBool($data['habilita_nfsen_recebidas_homologacao'] ?? null),
            enviar_email_destinatario: TypeCast::nullableBool($data['enviar_email_destinatario'] ?? null),
            enviar_email_homologacao: TypeCast::nullableBool($data['enviar_email_homologacao'] ?? null),
            discrimina_impostos: TypeCast::nullableBool($data['discrimina_impostos'] ?? null),
            habilita_contingencia_offline_nfce: TypeCast::nullableBool($data['habilita_contingencia_offline_nfce'] ?? null),
            reaproveita_numero_nfce_contingencia: TypeCast::nullableBool($data['reaproveita_numero_nfce_contingencia'] ?? null),
            csc_nfce_producao: $data['csc_nfce_producao'] ?? null,
            id_token_nfce_producao: TypeCast::nullableInt($data['id_token_nfce_producao'] ?? null),
            csc_nfce_homologacao: $data['csc_nfce_homologacao'] ?? null,
            id_token_nfce_homologacao: TypeCast::nullableInt($data['id_token_nfce_homologacao'] ?? null),
            orientacao_danfe: isset($data['orientacao_danfe'])
                ? OrientacaoDanfe::from($data['orientacao_danfe'])
                : null,
            recibo_danfe: TypeCast::nullableBool($data['recibo_danfe'] ?? null),
            exibe_sempre_ipi_danfe: TypeCast::nullableBool($data['exibe_sempre_ipi_danfe'] ?? null),
            exibe_issqn_danfe: TypeCast::nullableBool($data['exibe_issqn_danfe'] ?? null),
            exibe_impostos_adicionais_danfe: TypeCast::nullableBool($data['exibe_impostos_adicionais_danfe'] ?? null),
            exibe_rastro_danfe: TypeCast::nullableBool($data['exibe_rastro_danfe'] ?? null),
            exibe_unidade_tributaria_danfe: TypeCast::nullableBool($data['exibe_unidade_tributaria_danfe'] ?? null),
            exibe_sempre_volumes_danfe: TypeCast::nullableBool($data['exibe_sempre_volumes_danfe'] ?? null),
            exibe_composicao_carga_mdfe: TypeCast::nullableBool($data['exibe_composicao_carga_mdfe'] ?? null),
            mostrar_danfse_badge: TypeCast::nullableBool($data['mostrar_danfse_badge'] ?? null),
            proximo_numero_nfe_producao: $data['proximo_numero_nfe_producao'] ?? null,
            proximo_numero_nfe_homologacao: $data['proximo_numero_nfe_homologacao'] ?? null,
            serie_nfe_producao: $data['serie_nfe_producao'] ?? null,
            serie_nfe_homologacao: $data['serie_nfe_homologacao'] ?? null,
            proximo_numero_nfce_producao: $data['proximo_numero_nfce_producao'] ?? null,
            proximo_numero_nfce_homologacao: $data['proximo_numero_nfce_homologacao'] ?? null,
            serie_nfce_producao: $data['serie_nfce_producao'] ?? null,
            serie_nfce_homologacao: $data['serie_nfce_homologacao'] ?? null,
            proximo_numero_nfse_producao: $data['proximo_numero_nfse_producao'] ?? null,
            proximo_numero_nfse_homologacao: $data['proximo_numero_nfse_homologacao'] ?? null,
            serie_nfse_producao: $data['serie_nfse_producao'] ?? null,
            serie_nfse_homologacao: $data['serie_nfse_homologacao'] ?? null,
            proximo_numero_nfsen_producao: $data['proximo_numero_nfsen_producao'] ?? null,
            proximo_numero_nfsen_homologacao: $data['proximo_numero_nfsen_homologacao'] ?? null,
            serie_nfsen_producao: $data['serie_nfsen_producao'] ?? null,
            serie_nfsen_homologacao: $data['serie_nfsen_homologacao'] ?? null,
            proximo_numero_cte_producao: $data['proximo_numero_cte_producao'] ?? null,
            proximo_numero_cte_homologacao: $data['proximo_numero_cte_homologacao'] ?? null,
            serie_cte_producao: $data['serie_cte_producao'] ?? null,
            serie_cte_homologacao: $data['serie_cte_homologacao'] ?? null,
            proximo_numero_cte_os_producao: $data['proximo_numero_cte_os_producao'] ?? null,
            proximo_numero_cte_os_homologacao: $data['proximo_numero_cte_os_homologacao'] ?? null,
            serie_cte_os_producao: $data['serie_cte_os_producao'] ?? null,
            serie_cte_os_homologacao: $data['serie_cte_os_homologacao'] ?? null,
            proximo_numero_mdfe_producao: $data['proximo_numero_mdfe_producao'] ?? null,
            proximo_numero_mdfe_homologacao: $data['proximo_numero_mdfe_homologacao'] ?? null,
            serie_mdfe_producao: $data['serie_mdfe_producao'] ?? null,
            serie_mdfe_homologacao: $data['serie_mdfe_homologacao'] ?? null,
            proximo_numero_nfcom_producao: $data['proximo_numero_nfcom_producao'] ?? null,
            proximo_numero_nfcom_homologacao: $data['proximo_numero_nfcom_homologacao'] ?? null,
            serie_nfcom_producao: $data['serie_nfcom_producao'] ?? null,
            serie_nfcom_homologacao: $data['serie_nfcom_homologacao'] ?? null,
            arquivo_certificado_base64: $data['arquivo_certificado_base64'] ?? null,
            senha_certificado: $data['senha_certificado'] ?? null,
            arquivo_logo_base64: $data['arquivo_logo_base64'] ?? null,
            delete_logo: TypeCast::nullableBool($data['delete_logo'] ?? null),
            nome_responsavel: $data['nome_responsavel'] ?? null,
            cpf_responsavel: $data['cpf_responsavel'] ?? null,
            login_responsavel: $data['login_responsavel'] ?? null,
            senha_responsavel: $data['senha_responsavel'] ?? null,
            senha_responsavel_preenchida: TypeCast::nullableBool($data['senha_responsavel_preenchida'] ?? null),
            cpf_cnpj_contabilidade: $data['cpf_cnpj_contabilidade'] ?? null,
            data_inicio_recebimento_nfe: $data['data_inicio_recebimento_nfe'] ?? null,
            data_inicio_recebimento_cte: $data['data_inicio_recebimento_cte'] ?? null,
            smtp_endereco: $data['smtp_endereco'] ?? null,
            smtp_dominio: $data['smtp_dominio'] ?? null,
            smtp_porta: TypeCast::nullableInt($data['smtp_porta'] ?? null),
            smtp_autenticacao: isset($data['smtp_autenticacao'])
                ? SmtpAutenticacao::from($data['smtp_autenticacao'])
                : null,
            smtp_login: $data['smtp_login'] ?? null,
            smtp_senha: $data['smtp_senha'] ?? null,
            smtp_remetente: $data['smtp_remetente'] ?? null,
            smtp_responder_para: $data['smtp_responder_para'] ?? null,
            smtp_modo_verificacao_openssl: isset($data['smtp_modo_verificacao_openssl'])
                ? SmtpVerificacaoOpenssl::from($data['smtp_modo_verificacao_openssl'])
                : null,
            smtp_habilita_starttls: TypeCast::nullableBool($data['smtp_habilita_starttls'] ?? null),
            smtp_ssl: TypeCast::nullableBool($data['smtp_ssl'] ?? null),
            smtp_tls: TypeCast::nullableBool($data['smtp_tls'] ?? null),
            nfe_sincrono: TypeCast::nullableBool($data['nfe_sincrono'] ?? null),
            nfe_sincrono_homologacao: TypeCast::nullableBool($data['nfe_sincrono_homologacao'] ?? null),
            mdfe_sincrono: TypeCast::nullableBool($data['mdfe_sincrono'] ?? null),
            mdfe_sincrono_homologacao: TypeCast::nullableBool($data['mdfe_sincrono_homologacao'] ?? null),
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return array_filter([
            'nome' => $this->nome,
            'nome_fantasia' => $this->nome_fantasia,
            'cnpj' => $this->cnpj,
            'cpf' => $this->cpf,
            'inscricao_estadual' => $this->inscricao_estadual,
            'inscricao_municipal' => $this->inscricao_municipal,
            'regime_tributario' => $this->regime_tributario?->value,
            'logradouro' => $this->logradouro,
            'numero' => $this->numero,
            'complemento' => $this->complemento,
            'bairro' => $this->bairro,
            'municipio' => $this->municipio,
            'cep' => $this->cep,
            'uf' => $this->uf,
            'telefone' => $this->telefone,
            'email' => $this->email,
            'habilita_nfe' => $this->habilita_nfe,
            'habilita_nfce' => $this->habilita_nfce,
            'habilita_nfse' => $this->habilita_nfse,
            'habilita_nfsen_producao' => $this->habilita_nfsen_producao,
            'habilita_nfsen_homologacao' => $this->habilita_nfsen_homologacao,
            'habilita_cte' => $this->habilita_cte,
            'habilita_mdfe' => $this->habilita_mdfe,
            'habilita_nfcom' => $this->habilita_nfcom,
            'habilita_manifestacao' => $this->habilita_manifestacao,
            'habilita_manifestacao_cte' => $this->habilita_manifestacao_cte,
            'habilita_nfsen_recebidas_producao' => $this->habilita_nfsen_recebidas_producao,
            'habilita_nfsen_recebidas_homologacao' => $this->habilita_nfsen_recebidas_homologacao,
            'enviar_email_destinatario' => $this->enviar_email_destinatario,
            'enviar_email_homologacao' => $this->enviar_email_homologacao,
            'discrimina_impostos' => $this->discrimina_impostos,
            'habilita_contingencia_offline_nfce' => $this->habilita_contingencia_offline_nfce,
            'reaproveita_numero_nfce_contingencia' => $this->reaproveita_numero_nfce_contingencia,
            'csc_nfce_producao' => $this->csc_nfce_producao,
            'id_token_nfce_producao' => $this->id_token_nfce_producao,
            'csc_nfce_homologacao' => $this->csc_nfce_homologacao,
            'id_token_nfce_homologacao' => $this->id_token_nfce_homologacao,
            'orientacao_danfe' => $this->orientacao_danfe?->value,
            'recibo_danfe' => $this->recibo_danfe,
            'exibe_sempre_ipi_danfe' => $this->exibe_sempre_ipi_danfe,
            'exibe_issqn_danfe' => $this->exibe_issqn_danfe,
            'exibe_impostos_adicionais_danfe' => $this->exibe_impostos_adicionais_danfe,
            'exibe_rastro_danfe' => $this->exibe_rastro_danfe,
            'exibe_unidade_tributaria_danfe' => $this->exibe_unidade_tributaria_danfe,
            'exibe_sempre_volumes_danfe' => $this->exibe_sempre_volumes_danfe,
            'exibe_composicao_carga_mdfe' => $this->exibe_composicao_carga_mdfe,
            'mostrar_danfse_badge' => $this->mostrar_danfse_badge,
            'proximo_numero_nfe_producao' => $this->proximo_numero_nfe_producao,
            'proximo_numero_nfe_homologacao' => $this->proximo_numero_nfe_homologacao,
            'serie_nfe_producao' => $this->serie_nfe_producao,
            'serie_nfe_homologacao' => $this->serie_nfe_homologacao,
            'proximo_numero_nfce_producao' => $this->proximo_numero_nfce_producao,
            'proximo_numero_nfce_homologacao' => $this->proximo_numero_nfce_homologacao,
            'serie_nfce_producao' => $this->serie_nfce_producao,
            'serie_nfce_homologacao' => $this->serie_nfce_homologacao,
            'proximo_numero_nfse_producao' => $this->proximo_numero_nfse_producao,
            'proximo_numero_nfse_homologacao' => $this->proximo_numero_nfse_homologacao,
            'serie_nfse_producao' => $this->serie_nfse_producao,
            'serie_nfse_homologacao' => $this->serie_nfse_homologacao,
            'proximo_numero_nfsen_producao' => $this->proximo_numero_nfsen_producao,
            'proximo_numero_nfsen_homologacao' => $this->proximo_numero_nfsen_homologacao,
            'serie_nfsen_producao' => $this->serie_nfsen_producao,
            'serie_nfsen_homologacao' => $this->serie_nfsen_homologacao,
            'proximo_numero_cte_producao' => $this->proximo_numero_cte_producao,
            'proximo_numero_cte_homologacao' => $this->proximo_numero_cte_homologacao,
            'serie_cte_producao' => $this->serie_cte_producao,
            'serie_cte_homologacao' => $this->serie_cte_homologacao,
            'proximo_numero_cte_os_producao' => $this->proximo_numero_cte_os_producao,
            'proximo_numero_cte_os_homologacao' => $this->proximo_numero_cte_os_homologacao,
            'serie_cte_os_producao' => $this->serie_cte_os_producao,
            'serie_cte_os_homologacao' => $this->serie_cte_os_homologacao,
            'proximo_numero_mdfe_producao' => $this->proximo_numero_mdfe_producao,
            'proximo_numero_mdfe_homologacao' => $this->proximo_numero_mdfe_homologacao,
            'serie_mdfe_producao' => $this->serie_mdfe_producao,
            'serie_mdfe_homologacao' => $this->serie_mdfe_homologacao,
            'proximo_numero_nfcom_producao' => $this->proximo_numero_nfcom_producao,
            'proximo_numero_nfcom_homologacao' => $this->proximo_numero_nfcom_homologacao,
            'serie_nfcom_producao' => $this->serie_nfcom_producao,
            'serie_nfcom_homologacao' => $this->serie_nfcom_homologacao,
            'arquivo_certificado_base64' => $this->arquivo_certificado_base64,
            'senha_certificado' => $this->senha_certificado,
            'arquivo_logo_base64' => $this->arquivo_logo_base64,
            'delete_logo' => $this->delete_logo,
            'nome_responsavel' => $this->nome_responsavel,
            'cpf_responsavel' => $this->cpf_responsavel,
            'login_responsavel' => $this->login_responsavel,
            'senha_responsavel' => $this->senha_responsavel,
            'senha_responsavel_preenchida' => $this->senha_responsavel_preenchida,
            'cpf_cnpj_contabilidade' => $this->cpf_cnpj_contabilidade,
            'data_inicio_recebimento_nfe' => $this->data_inicio_recebimento_nfe,
            'data_inicio_recebimento_cte' => $this->data_inicio_recebimento_cte,
            'smtp_endereco' => $this->smtp_endereco,
            'smtp_dominio' => $this->smtp_dominio,
            'smtp_porta' => $this->smtp_porta,
            'smtp_autenticacao' => $this->smtp_autenticacao?->value,
            'smtp_login' => $this->smtp_login,
            'smtp_senha' => $this->smtp_senha,
            'smtp_remetente' => $this->smtp_remetente,
            'smtp_responder_para' => $this->smtp_responder_para,
            'smtp_modo_verificacao_openssl' => $this->smtp_modo_verificacao_openssl?->value,
            'smtp_habilita_starttls' => $this->smtp_habilita_starttls,
            'smtp_ssl' => $this->smtp_ssl,
            'smtp_tls' => $this->smtp_tls,
            'nfe_sincrono' => $this->nfe_sincrono,
            'nfe_sincrono_homologacao' => $this->nfe_sincrono_homologacao,
            'mdfe_sincrono' => $this->mdfe_sincrono,
            'mdfe_sincrono_homologacao' => $this->mdfe_sincrono_homologacao,
        ], fn (mixed $v): bool => $v !== null);
    }
}
